---
title: "Taxa Prediction"
format: html
editor: visual
---

```{r}

library(tidyverse)
library(here)
library(patchwork)
library(missForest)
library(tidymodels)
library(ggpubr)
library(progress)
library(pROC)
library(effsize)
```

```{r functions}


calculate_non_parametric_stats <- function(continuous_var, binary_var) 
{
  binary_var <- droplevels(binary_var) 
  delta_result <- cliff.delta(continuous_var, binary_var)
  wilcox_test_result <- wilcox.test(continuous_var ~ binary_var)
  return(tibble(
    cliffs_delta = delta_result$estimate,
    p_wilcox = wilcox_test_result$p.value
  ))
}

calculate_parametric_stats <- function(continuous_var, binary_var) {
  binary_var <- droplevels(as.factor(binary_var))
  if (nlevels(binary_var) != 2) stop("binary_var must have 2 levels")

  lvl <- levels(binary_var)
  g1 <- continuous_var[binary_var == lvl[1]]
  g2 <- continuous_var[binary_var == lvl[2]]

  # Welch t-test
  tt <- t.test(g1, g2, var.equal = FALSE)

  # Cohen’s d (classic pooled)
  n1 <- length(g1); n2 <- length(g2)
  s1 <- sd(g1);     s2 <- sd(g2)
  pooled_sd <- sqrt(((n1 - 1)*s1^2 + (n2 - 1)*s2^2) / (n1 + n2 - 2))
  cohen_d <- (mean(g1) - mean(g2)) / pooled_sd

  # Hedges g correction
  J <- 1 - 3 / (4*(n1 + n2 - 2) - 1)
  hedges_g <- cohen_d * J

  tibble(
    cohen_d = cohen_d,
    hedges_g = hedges_g,
    p_ttest = tt$p.value
  )
}


rf_class_vfold <- function(df, workflow, n_folds = 5, seed_value = 333) {
  set.seed(seed_value)
  cv_folds <- vfold_cv(df, v = n_folds)
  
  model_spec <- extract_spec_parsnip(workflow)
  metrics = metric_set(roc_auc, accuracy, sensitivity, specificity)
  
  get_importance_universal <- function(x) {
    model <- extract_fit_parsnip(x)
    
    imp <- tryCatch({
      vip::vi(model)
    }, error = function(e) {
      tryCatch({
        tidy(model) %>%
          filter(term != "(Intercept)") %>%
          mutate(Importance = abs(estimate)) %>%
          select(Variable = term, Importance)
      }, error = function(e) {
        NULL
      })
    })
    return(imp)
  }
  
  cv_results <- fit_resamples(
    workflow,
    resamples = cv_folds,
    metrics = metrics,
    control = control_resamples(
      save_pred = TRUE, 
      save_workflow = TRUE,
      extract = get_importance_universal
    )
  )
  
  df_pred <- cv_results %>%
    collect_predictions() %>%
    bind_cols(
      df %>% select(sample_id) %>% slice(cv_results %>% collect_predictions() %>% pull(.row))
    )
  
  df_imp <- tryCatch({
    cv_results %>%
      select(id, .extracts) %>%
      unnest(cols = .extracts) %>%
      unnest(cols = .extracts) %>%
      filter(!is.null(Variable))
  }, error = function(e) NULL)
  
  df_metrics <- collect_metrics(cv_results, summarize = FALSE) %>%
    group_by(.metric) %>%
    mutate(mean = mean(.estimate), sd = sd(.estimate)) %>%
    ungroup()
  
  return(list(
    'df_metrics' = df_metrics, 
    'df_pred' = df_pred, 
    'df_imp' = df_imp,
    'cv_results' = cv_results
  ))
}


```

# Prep Data

```{r}


df_meta = read.csv(here('data', 'df_meta.csv'))
df_meta_qual = read.csv(here('data', 'df_meta_qual.csv'))
df_meta_mp = read.csv(here('data', 'df_meta_mp.csv'))

df_mp = read.csv(here('data', 'df_mp.csv')) |> filter(statq == 'statq_0.20')

mat_qual_plasma = read.csv(here('data', 'AML_plasma', 'mat_qual_plasma.csv')) |> column_to_rownames('X') |> as.matrix()

mat_qual_plasma = as.data.frame(mat_qual_plasma) |> 
  rownames_to_column('sample_id') |> 
  select(-QUAL074) |> 
  left_join(
    rbind(
      read.csv(here('data', 'AML_plasma', 'normalized_results_20251217_isoUDCA_MDCA_AMLplasma.csv'), check.names = F),
      read.csv(here('data', 'AML_plasma', 'normalized_results_isoUDCA_MDCA_AML00112_AML00307.csv'), check.names = F)
      ) |>  
      mutate(sampleid = gsub('\\.', '', sampleid)) |> 
      left_join(df_meta |> select(sampleid = metabolomics_id_plasma, sample_id), by = 'sampleid') |> 
      select(-sampleid) |> 
      rename_with(~ case_when(
        .x == "isoursodeoxycholic acid"  ~ "QUAL074_1",
        .x == "murideoxycholic acid"  ~ "QUAL074_2",
        T ~ .x
      )) |> 
      mutate(QUAL074_1 = ifelse(is.na(QUAL074_1), 0, QUAL074_1)) |>
      mutate(QUAL074_2 = ifelse(is.na(QUAL074_2), 0, QUAL074_2)),
    by = 'sample_id'
    ) |> 
  column_to_rownames('sample_id') |> 
  as.matrix()


```

```{r}

mat_mps = df_mp |> 
  filter(seq_id %in% df_meta$seq_id) |> 
  left_join(df_meta |> select(sample_id, seq_id), by = 'seq_id') |> 
  select(sample_id, species, ra) |> 
  pivot_wider(id_cols = sample_id, names_from = species, values_from = ra, values_fill = 0) |> 
  column_to_rownames('sample_id') |> 
  as.matrix()

mat_mpg = mat_mps |> 
  as.data.frame() |> 
  rownames_to_column('sample_id') |> 
  pivot_longer(!sample_id, names_to = 'species', values_to = 'ra') |> 
  left_join(df_meta_mp, by = 'species') |> 
  
  group_by(sample_id, genus) |> 
  summarize(ra = sum(ra), .groups = 'drop') |> 
  ungroup() |> 
  
  pivot_wider(id_cols = sample_id, names_from = genus, values_from = ra, values_fill = 0) |> 
  column_to_rownames('sample_id') |> 
  as.matrix()

mat_mpf = mat_mps |> 
  as.data.frame() |> 
  rownames_to_column('sample_id') |> 
  pivot_longer(!sample_id, names_to = 'species', values_to = 'ra') |> 
  left_join(df_meta_mp, by = 'species') |> 
  
  group_by(sample_id, family) |> 
  summarize(ra = sum(ra), .groups = 'drop') |> 
  ungroup() |> 
  
  pivot_wider(id_cols = sample_id, names_from = family, values_from = ra, values_fill = 0) |> 
  column_to_rownames('sample_id') |> 
  as.matrix()

mat_mpo = mat_mps |> 
  as.data.frame() |> 
  rownames_to_column('sample_id') |> 
  pivot_longer(!sample_id, names_to = 'species', values_to = 'ra') |> 
  left_join(df_meta_mp, by = 'species') |> 
  
  group_by(sample_id, order) |> 
  summarize(ra = sum(ra), .groups = 'drop') |> 
  ungroup() |> 
  
  pivot_wider(id_cols = sample_id, names_from = order, values_from = ra, values_fill = 0) |> 
  column_to_rownames('sample_id') |> 
  as.matrix()

mat_mpc = mat_mps |> 
  as.data.frame() |> 
  rownames_to_column('sample_id') |> 
  pivot_longer(!sample_id, names_to = 'species', values_to = 'ra') |> 
  left_join(df_meta_mp, by = 'species') |> 
  
  group_by(sample_id, class) |> 
  summarize(ra = sum(ra), .groups = 'drop') |> 
  ungroup() |> 
  
  pivot_wider(id_cols = sample_id, names_from = class, values_from = ra, values_fill = 0) |> 
  column_to_rownames('sample_id') |> 
  as.matrix()

mat_mpp = mat_mps |> 
  as.data.frame() |> 
  rownames_to_column('sample_id') |> 
  pivot_longer(!sample_id, names_to = 'species', values_to = 'ra') |> 
  left_join(df_meta_mp, by = 'species') |> 
  
  group_by(sample_id, phylum) |> 
  summarize(ra = sum(ra), .groups = 'drop') |> 
  ungroup() |> 
  
  pivot_wider(id_cols = sample_id, names_from = phylum, values_from = ra, values_fill = 0) |> 
  column_to_rownames('sample_id') |> 
  as.matrix()

```

```{r}

mat_alphadiv = data.frame(
  shannon = diversity(mat_mps, index = "shannon"),
  shannon_genus = diversity(mat_mpg, index = "shannon"),
  inv_simpson = diversity(mat_mps, index = "invsimpson"),
  richness = specnumber(mat_mps)
) |> 
  as.matrix()


```

```{r}

matrices_names = c(
  'mat_mps', 'mat_mpg', 'mat_mpf', 'mat_mpo', 'mat_mpc', 'mat_mpp',
  'mat_qual_plasma', 'mat_alphadiv'
  )

matrices = mget(matrices_names)
common_rows = Reduce(intersect, lapply(matrices, rownames)) 
matrices = lapply(matrices, function(m) m[common_rows, ])
list2env(setNames(matrices, matrices_names), envir = .GlobalEnv)

df_meta = df_meta[match(rownames(get(matrices_names[1])), df_meta$sample_id), ]
df_mp = df_mp |> filter(seq_id %in% df_meta$seq_id)

```

```{r}

seed_value = 333
n_folds = 5
nboot = 2000

pseudo_mat_qual_plasma = min(mat_qual_plasma[mat_qual_plasma > 0], na.rm = T)*0.1


families_of_interest = c(
  'Lachnospiraceae', 
  'Oscillospiraceae', 
  'Bacteroidaceae'
  ) 

taxa_family_colors = c(
  'Enterococcaceae' = "#129246", 
  'Enterobacteriaceae' = "red", 
  'Lachnospiraceae' = "#EC9B96", 
  'Oscillospiraceae' = "#9AAE73", 
  'Bacteroidaceae' = "#51AB9B"
)
```

# Main

## 3a) Classification Performance

```{r}


class_rf_spec = rand_forest(
  mtry = floor(sqrt(ncol(X))),
  min_n = 5,
  trees = 500
) %>%
  set_engine("ranger", importance = "permutation") %>%
  set_mode("classification")

class_ridge_spec = logistic_reg(
  penalty = 0.01,
  mixture = 0
) %>%
  set_engine("glmnet") %>%
  set_mode("classification")

class_lasso_spec = logistic_reg(
  penalty = 0.01,
  mixture = 1
) %>%
  set_engine("glmnet") %>%
  set_mode("classification")

class_xgb_spec = boost_tree(
  mtry = floor(sqrt(ncol(X))),
  trees = 500,
  min_n = 5
) %>%
  set_engine("xgboost") %>%
  set_mode("classification")

class_logreg_spec = logistic_reg() %>%
  set_engine("glm") %>%
  set_mode("classification")


```

```{r}

X = apply(mat_qual_plasma, 2, function(x) log10(x + pseudo_mat_qual_plasma))

Y = ifelse(mat_mpf > 0, 1, 0)
Y = Y[, colSums(Y) != 0 & colSums(Y) != nrow(Y)]
Y = Y[, colSums(Y == 0) <= 184 & colSums(Y == 1) <= 184] # At least 10 samples with differnt values

pb = progress_bar$new(format = "[:bar] :percent  (:current/:total) ETA::eta", total = ncol(Y), clear = F, width = 60)
res_rfclass_vfold_aml_mpf = list()
res_xgbclass_vfold_aml_mpf= list()
res_ridgeclass_vfold_aml_mpf = list()
res_lassoclass_vfold_aml_mpf = list()

for(col in colnames(Y))
{
  pb$tick()
  y = Y[, col]
  y = factor(ifelse(y == 1, 'Present', 'Absent'), levels = c('Present', 'Absent'))
  
  df = as.data.frame(X) |>rownames_to_column('sample_id') |> mutate(y = y)

  recipe = recipe(y ~ ., data = df) |> 
    update_role(sample_id, new_role = "sample_id") |> 
    step_normalize(all_predictors()) 

  workflow = workflow() |> add_recipe(recipe)
  
  res_rfclass_vfold_aml_mpf[[col]] = rf_class_vfold(df, workflow |> add_model(class_rf_spec), 5, 333)
  res_xgbclass_vfold_aml_mpf[[col]] = rf_class_vfold(df, workflow |> add_model(class_xgb_spec), 5, 333)
  res_ridgeclass_vfold_aml_mpf[[col]] = rf_class_vfold(df, workflow |> add_model(class_ridge_spec), 5, 333)
  res_lassoclass_vfold_aml_mpf[[col]] = rf_class_vfold(df, workflow |> add_model(class_lasso_spec), 5, 333)
}

```

```{r}

selected_features  = c(
  'QUAL016', # IPA
  'QUAL074_1', # isoUDCA
  "QUAL072", # isoDCA
  "QUAL138", # isoCDCA
  "QUAL058", # DCA
  "QUAL065", # GDCA
  "QUAL137", # GLCA-3S
  "QUAL063" # GCA
  )

X = apply(mat_qual_plasma, 2, function(x) log10(x + pseudo_mat_qual_plasma))
X = X[, selected_features]


Y = ifelse(mat_mpf > 0, 1, 0)
Y = Y[, colSums(Y) != 0 & colSums(Y) != nrow(Y)]
Y = Y[, colSums(Y == 0) <= 184 & colSums(Y == 1) <= 184] # At least 10 samples with differnt values

pb = progress_bar$new(format = "[:bar] :percent  (:current/:total) ETA::eta", total = ncol(Y), clear = F, width = 60)

res_rfclass_vfold_aml_mpf_reduced = list()
res_xgbclass_vfold_aml_mpf_reduced = list()
res_ridgeclass_vfold_aml_mpf_reduced = list()
res_lassoclass_vfold_aml_mpf_reduced = list()

for(col in colnames(Y))
{
  pb$tick()
  y = Y[, col]
  y = factor(ifelse(y == 1, 'Present', 'Absent'), levels = c('Present', 'Absent'))
  
  df = as.data.frame(X) |>rownames_to_column('sample_id') |> mutate(y = y)

  recipe = recipe(y ~ ., data = df) |> 
    update_role(sample_id, new_role = "sample_id") |> 
    step_normalize(all_predictors()) 

  workflow = workflow() |> add_recipe(recipe)
  
  res_rfclass_vfold_aml_mpf_reduced[[col]] = rf_class_vfold(df, workflow |> add_model(class_rf_spec), 5, 333)
  res_xgbclass_vfold_aml_mpf_reduced[[col]] = rf_class_vfold(df, workflow |> add_model(class_xgb_spec), 5, 333)
  res_ridgeclass_vfold_aml_mpf_reduced[[col]] = rf_class_vfold(df, workflow |> add_model(class_ridge_spec), 5, 333)
  res_lassoclass_vfold_aml_mpf_reduced[[col]] = rf_class_vfold(df, workflow |> add_model(class_lasso_spec), 5, 333)
}



```

```{r}

roc_data <- map_dfr(families_of_interest, function(taxon) {
  dfp <- res_rfclass_vfold_aml_mpf[[taxon]]$df_pred
  r <- roc(dfp$y, dfp$.pred_Present, quiet = TRUE)
  coords(r, "all", ret = c("specificity", "sensitivity"), transpose = FALSE) %>%
    as.data.frame() %>%
    mutate(taxon = taxon, fpr = 1 - specificity, tpr = sensitivity)
}) |> 
  mutate(taxon = factor(taxon, levels = families_of_interest))

auc_labels <- map_dfr(families_of_interest, function(taxon) {
  dfp <- res_rfclass_vfold_aml_mpf[[taxon]]$df_pred
  r <- roc(dfp$y, dfp$.pred_Present, quiet = TRUE)
  ci <- ci.auc(r, method = "bootstrap", boot.n = 2000, quiet = TRUE)
  tibble(
    taxon = taxon, 
    auc = as.numeric(auc(r)),
    lo = as.numeric(ci[1]),
    hi = as.numeric(ci[3])
  )
}) %>%
  arrange(desc(auc)) %>%
  mutate(label = sprintf("%s: %.2f [%.2f–%.2f]", taxon, auc, lo, hi))

best_points <- map_dfr(families_of_interest, function(taxon) {
  dfp <- res_rfclass_vfold_aml_mpf[[taxon]]$df_pred
  r <- roc(dfp$y, dfp$.pred_Present, quiet = TRUE)
  best <- coords(r, "best", best.method = "youden", ret = c("threshold", "specificity", "sensitivity"))
  tibble(
    taxon = taxon,
    fpr = 1 - best$specificity,
    tpr = best$sensitivity,
    threshold = best$threshold
  )
})


p_3a = ggplot(roc_data, aes(x = fpr, y = tpr, color = taxon)) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "grey60") +
  geom_path(linewidth = 1) +
  geom_point(
    data = best_points, aes(x = fpr, y = tpr, fill = taxon), 
    size = 2, shape = 23, color = "black", stroke = 1
    ) +
  scale_color_manual(values = taxa_family_colors, labels = setNames(auc_labels$label, auc_labels$taxon), name = NULL) +
  scale_fill_manual(values = taxa_family_colors) +
  guides(fill = "none") +
  labs(x = "False Positive Rate (1 - Specificity)", y = "True Positive Rate (Sensitivity)") +
  theme_bw(base_size = 15) +
  theme(
    legend.position = c(0.72, 0.23),
    legend.box.background = element_rect(color = "grey40", linewidth = 0.5)
    )

```

```{r}

pdf(here('output', paste0('fig3a_', format(Sys.Date(), "%Y%m%d"), '.pdf')), height = 4, width = 7)
p_3a
dev.off()

```

## 3b) Feature Importance

```{r}

df_mpf_effectsize = as.data.frame(mat_qual_plasma) %>%
  rownames_to_column('sample_id') |> 
  pivot_longer(!sample_id, names_to = "compound_id", values_to = "value") %>%
  left_join(
    as.data.frame(apply(mat_mpf, 2, function(col) ifelse(col > 0, "Present", "Absent"))) %>%
      rownames_to_column('sample_id') |>
      pivot_longer(!sample_id, names_to = "taxa", values_to = "presence"),
    by = "sample_id", relationship = "many-to-many"
  ) %>%
  mutate(presence = factor(presence, levels = c('Present', 'Absent'))) |> 
  group_by(compound_id, taxa) %>%
  filter(n_distinct(presence) == 2) %>%
  summarise(stats = list(calculate_non_parametric_stats(value, presence)), .groups = 'drop') %>%
  unnest(stats) |> 
  left_join(df_meta_qual |> select(compound_id, hmmf_panel, compound), by = 'compound_id')

df_imp = imap_dfr(
  res_rfclass_vfold_aml_mpf,
  ~ .x$df_imp |> mutate(taxa = .y)
  ) |> 
  mutate(Importance = pmax(Importance, 0)) |> 
  group_by(id, taxa) |> 
  mutate(imp_scaled = Importance/sum(Importance)) |> 
  ungroup() |> 
  group_by(Variable, taxa) |> 
  summarize(
    imp_mean = mean(imp_scaled),
    imp_sd = sd(imp_scaled),
    .groups = 'drop'
  ) |> 
  rename(compound_id = Variable) |> 
  left_join(df_meta_qual |> select(compound_id, compound, hmmf_panel, category), by = 'compound_id') |> 
  left_join(df_mpf_effectsize |> select(compound_id, taxa, cliffs_delta, p_wilcox), by = c('compound_id', 'taxa')) |> 
  mutate(p_adj = p.adjust(p_wilcox, method = "BH")) |> 
  mutate(p_adj_cat = case_when(
    p_adj > 0.05 ~ 'NS',
    p_adj > 0.01 & p_adj <= 0.05 ~ '*',
    p_adj > 0.001 & p_adj <= 0.01 ~ '**',
    p_adj < 0.001 ~ '***',
    T ~ NA
  ))


```

```{r}

selected_categories = c(
  'Primary',
  'Primary conjugate',
  'Primary sulfate',
  'Secondary',
  'Secondary conjugate',
  'Secondary sulfate',
  '3β-epimer',
  
  'Substrate', 
  'Microbial indole'
  )

mat = df_imp %>%
  filter(taxa %in% families_of_interest) |> 
  filter(category %in% selected_categories) |> 
  select(compound, taxa, imp_mean) %>% 
  pivot_wider(names_from = taxa, values_from = imp_mean, values_fill = 0)

m <- as.matrix(mat[, families_of_interest])
rownames(m) <- mat$compound
row_order <- rownames(m)[ hclust(dist(m))$order ]

df_plot <- df_imp %>%
  filter(taxa %in% families_of_interest) |> 
  filter(compound %in% rownames(m)) |> 
  mutate(
    compound = factor(compound, levels = row_order),
    taxa = factor(taxa, levels = families_of_interest),
    category = factor(category, levels = selected_categories),
    sig_lab  = case_when(
      p_adj < 0.001 ~ "***",
      p_adj < 0.01  ~ "**",
      p_adj < 0.05  ~ "*",
      T ~ ""
    )
  ) |> 
  mutate(imp_mean = ifelse(cliffs_delta < 0, -imp_mean, imp_mean))

p_3b = ggplot(df_plot, aes(x = taxa, y = compound)) +
  geom_point(
    aes(size = abs(imp_mean), fill = cliffs_delta),
    shape = 21, color = "black", stroke = 0.25
  ) +
  scale_fill_gradient2(high = '#b2182b', mid = 'white', low = '#2166ac', midpoint = 0, limits = c(-1,1), name = "Cliff's δ") +
  scale_size(range = c(1.5, 8), name = "Scaled\nImportance") +
  facet_grid(rows = vars(category), scales = "free_y", space = "free_y") +
  theme_bw(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    strip.text.y.right = element_text(angle = 0),
    legend.position = 'right'
  )



```

```{r fig.height=9, fig.width=8}

cairo_pdf(here('output', paste0('fig3b_', format(Sys.Date(), "%Y%m%d"), '.pdf')), height = 9, width = 6)
p_3b
dev.off()

```

## 3c) ROC Curves Reduced

```{r}

roc_data <- map_dfr(families_of_interest, function(taxon) {
  dfp <- res_rfclass_vfold_aml_mpf_reduced[[taxon]]$df_pred
  r <- roc(dfp$y, dfp$.pred_Present, quiet = TRUE)
  coords(r, "all", ret = c("specificity", "sensitivity"), transpose = FALSE) %>%
    as.data.frame() %>%
    mutate(taxon = taxon, fpr = 1 - specificity, tpr = sensitivity)
}) |> 
  mutate(taxon = factor(taxon, levels = families_of_interest))

auc_labels <- map_dfr(families_of_interest, function(taxon) {
  dfp <- res_rfclass_vfold_aml_mpf_reduced[[taxon]]$df_pred
  r <- roc(dfp$y, dfp$.pred_Present, quiet = TRUE)
  ci <- ci.auc(r, method = "bootstrap", boot.n = 2000, quiet = TRUE)
  tibble(
    taxon = taxon, 
    auc = as.numeric(auc(r)),
    lo = as.numeric(ci[1]),
    hi = as.numeric(ci[3])
  )
}) %>%
  arrange(desc(auc)) %>%
  mutate(label = sprintf("%s: %.2f [%.2f–%.2f]", taxon, auc, lo, hi))

best_points <- map_dfr(families_of_interest, function(taxon) {
  dfp <- res_rfclass_vfold_aml_mpf_reduced[[taxon]]$df_pred
  r <- roc(dfp$y, dfp$.pred_Present, quiet = TRUE)
  best <- coords(r, "best", best.method = "youden", ret = c("threshold", "specificity", "sensitivity"))
  tibble(
    taxon = taxon,
    fpr = 1 - best$specificity,
    tpr = best$sensitivity,
    threshold = best$threshold
  )
})


p_3c = ggplot(roc_data, aes(x = fpr, y = tpr, color = taxon)) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "grey60") +
  geom_path(linewidth = 1) +
  geom_point(
    data = best_points, aes(x = fpr, y = tpr, fill = taxon), 
    size = 2, shape = 23, color = "black", stroke = 1
    ) +
  scale_color_manual(values = taxa_family_colors, labels = setNames(auc_labels$label, auc_labels$taxon), name = NULL) +
  scale_fill_manual(values = taxa_family_colors) +
  guides(fill = "none") +
  labs(x = "False Positive Rate (1 - Specificity)", y = "True Positive Rate (Sensitivity)") +
  theme_bw(base_size = 15) +
  theme(legend.position = c(0.7, 0.25),
        legend.background = element_blank())

```

```{r}

pdf(here('output', paste0('fig3c_', format(Sys.Date(), "%Y%m%d"), '.pdf')), height = 4, width = 7)
p_3c
dev.off()

```

## 3d) Boxplots

```{r}

cols = c("Absent" = "#999999", "Present" = "#0072B2")

p3d_1 = mat_qual_plasma |> 
  as.data.frame() |> 
  rownames_to_column("sample_id") |> 
  pivot_longer(-sample_id, names_to = "compound_id", values_to = "value") |> 
  left_join(df_meta_qual |> select(compound_id, compound, hmmf_panel), by = "compound_id") |> 
  filter(compound %in% 'IPA') |> 
  left_join(
    mat_mpf |> 
      as.data.frame() |> 
      rownames_to_column("sample_id") |> 
      pivot_longer(-sample_id, names_to = "family", values_to = "ra") |> 
      filter(family %in% families_of_interest),
    by = "sample_id"
  ) |> 
  mutate(
    presence = factor(ifelse(ra == 0, "Absent", "Present"), levels = c("Absent", "Present")),
    family  = factor(family, levels = families_of_interest)
  ) |> 
  ggplot(aes(x = family, y = value, fill = presence, color = presence, group = interaction(family, presence))) +
  geom_boxplot(width = 0.6, alpha = 0.8, outlier.shape = NA, position = position_dodge(width = 0.7), color = "black") +
  geom_point( position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.7), alpha = 0.5, size = 1.8) +
  scale_fill_manual(values = cols) +
  scale_color_manual(values = cols) +
  theme_minimal(base_size = 15) +
  labs(x = NULL, y = "log10 (Norm Peak Area)") +
  theme(
    axis.line = element_line(color = "black"),
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
  scale_y_continuous(
    trans = pseudo_log_trans(sigma = 0.0001), 
    breaks = c(0, 0.001, 0.01, 0.1),
    labels = scales::label_number()
    ) +
  stat_compare_means(
    aes(group = presence),
    method = "wilcox.test",
    label = "p.signif",  
    bracket.size = 0.6,
    tip.length = 0,
    label.y = 6,
    vjust = .03,
    size=5
    )


p3d_2 = mat_qual_plasma |> 
  as.data.frame() |> 
  rownames_to_column("sample_id") |> 
  pivot_longer(-sample_id, names_to = "compound_id", values_to = "value") |> 
  left_join(df_meta_qual |> select(compound_id, compound, hmmf_panel), by = "compound_id") |> 
  filter(compound %in% 'isoCDCA') |> 
  left_join(
    mat_mpf |> 
      as.data.frame() |> 
      rownames_to_column("sample_id") |> 
      pivot_longer(-sample_id, names_to = "family", values_to = "ra") |> 
      filter(family %in% families_of_interest),
    by = "sample_id"
  ) |> 
  mutate(
    presence = factor(ifelse(ra == 0, "Absent", "Present"), levels = c("Absent", "Present")),
    family  = factor(family, levels = families_of_interest)
  ) |> 
  ggplot(aes(x = family, y = value, fill = presence, color = presence, group = interaction(family, presence))) +
  geom_boxplot(width = 0.6, alpha = 0.8, outlier.shape = NA, position = position_dodge(width = 0.7), color = "black") +
  geom_point( position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.7), alpha = 0.5, size = 1.8) +
  scale_fill_manual(values = cols) +
  scale_color_manual(values = cols) +
  theme_minimal(base_size = 15) +
  labs(x = NULL, y = "log10 (Norm Peak Area)") +
  theme(
    axis.line = element_line(color = "black"),
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
  scale_y_continuous(
    trans = pseudo_log_trans(sigma = 0.0001), 
    breaks = c(0, 0.001, 0.01, 0.1, 1),
    labels = scales::label_number()
    ) +
  stat_compare_means(
    aes(group = presence),
    method = "wilcox.test",
    label = "p.signif",  
    bracket.size = 0.6,
    tip.length = 0,
    label.y = 7,
    vjust = .03,
    size=5
    )


p3d_3 = mat_qual_plasma |> 
  as.data.frame() |> 
  rownames_to_column("sample_id") |> 
  pivot_longer(-sample_id, names_to = "compound_id", values_to = "value") |> 
  left_join(df_meta_qual |> select(compound_id, compound, hmmf_panel), by = "compound_id") |> 
  filter(compound %in% 'GCA') |> 
  left_join(
    mat_mpf |> 
      as.data.frame() |> 
      rownames_to_column("sample_id") |> 
      pivot_longer(-sample_id, names_to = "family", values_to = "ra") |> 
      filter(family %in% families_of_interest),
    by = "sample_id"
  ) |> 
  mutate(
    presence = factor(ifelse(ra == 0, "Absent", "Present"), levels = c("Absent", "Present")),
    family  = factor(family, levels = families_of_interest)
  ) |> 
  ggplot(aes(x = family, y = value, fill = presence, color = presence, group = interaction(family, presence))) +
  geom_boxplot(width = 0.6, alpha = 0.8, outlier.shape = NA, position = position_dodge(width = 0.7), color = "black") +
  geom_point( position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.7), alpha = 0.5, size = 1.8) +
  scale_fill_manual(values = cols) +
  scale_color_manual(values = cols) +
  theme_minimal(base_size = 15) +
  labs(x = NULL, y = "log10 (Norm Peak Area)") +
  theme(
    axis.line = element_line(color = "black"),
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
  scale_y_continuous(
    trans = pseudo_log_trans(sigma = 0.0001), 
    breaks = c(0, 0.001, 0.01, 0.1, 1, 10),
    labels = scales::label_number()
    ) +
  stat_compare_means(
    aes(group = presence),
    method = "wilcox.test",
    label = "p.signif",  
    bracket.size = 0.6,
    tip.length = 0,
    label.y = 9,
    vjust = .03,
    size=5
    )
```

```{r}

pdf(here('output', paste0('fig3d_', format(Sys.Date(), "%Y%m%d"), '.pdf')), height = 3.5, width = 6)
p3d_1
p3d_2
p3d_3
dev.off()


```

# Supplemental

## Tables

```{r}

bind_rows(
  map_df(names(res_rfclass_vfold_aml_mpf), ~
    res_rfclass_vfold_aml_mpf[[.x]]$df_metrics %>%
      mutate(type = "Full Set (62 Metabolites)", taxa = .x)
  ),
  map_df(names(res_rfclass_vfold_aml_mpf_reduced), ~
    res_rfclass_vfold_aml_mpf_reduced[[.x]]$df_metrics %>%
      mutate(type = "Reduced Set (8 Metabolites)", taxa = .x)
  )
) |> 
  select(type, taxa, fold = id, metric = .metric, estimate = .estimate) |> 
  pivot_wider(id_cols = c(type, taxa, fold), names_from = metric, values_from = estimate) |> 
  write.csv(here('output', 'tableS7_taxpred_model_perf.csv'), row.names = F)


```

## Classification Performance

```{r}

pb = progress_bar$new(format = "[:bar] :percent  (:current/:total) ETA::eta", 
                      total = length(names(res_rfclass_vfold_aml_mpf)), clear = F, width = 60)

temp_list = list()
for(selected_tax in names(res_rfclass_vfold_aml_mpf))
{
  pb$tick()
  df_pred <- res_rfclass_vfold_aml_mpf[[selected_tax]]$df_pred
  df_pred$y_bin <- ifelse(df_pred$y == "Present", 1, 0)
  
  roc_pooled <- roc(df_pred$y_bin, df_pred$.pred_Present, quiet = T)
  best_coords <- coords(roc_pooled, "best", ret = c("threshold", "sensitivity", "specificity"), transpose = F)
  
  # Bootstrap
  boot_metrics <- replicate(2000, {
    idx <- sample(nrow(df_pred), replace = T)
    y_b <- df_pred$y_bin[idx]
    p_b <- df_pred$.pred_Present[idx]
    if(length(unique(y_b)) < 2) return(c(auc = NA, sens = NA, spec = NA))
    r <- roc(y_b, p_b, quiet = TRUE)
    coords_b <- coords(r, "best", ret = c("sensitivity", "specificity"), transpose = F)
    c(auc = as.numeric(auc(r)), 
      sens = coords_b$sensitivity[1], 
      spec = coords_b$specificity[1])
  })
  
  ci_vals <- apply(boot_metrics, 1, quantile, probs = c(0.025, 0.975), na.rm = T)
  
  temp_list[[selected_tax]] <- tibble(
    taxa = selected_tax,
    auc = as.numeric(auc(roc_pooled)),
    auc_lo = ci_vals["2.5%", "auc"],
    auc_hi = ci_vals["97.5%", "auc"],
    sens = best_coords$sensitivity[1],
    sens_lo = ci_vals["2.5%", "sens"],
    sens_hi = ci_vals["97.5%", "sens"],
    spec = best_coords$specificity[1],
    spec_lo = ci_vals["2.5%", "spec"],
    spec_hi = ci_vals["97.5%", "spec"]
  )
}

df_metrics = do.call(rbind, temp_list) |> 
  `rownames<-`(NULL) 

df_class_counts = map_dfr(names(res_rfclass_vfold_aml_mpf), function(selected_tax) {
  df_pred <- res_rfclass_vfold_aml_mpf[[selected_tax]]$df_pred
  df_pred %>%
    summarise(
      n_present = sum(y == "Present"),
      n_absent = sum(y == "Absent"),
      prevalence = mean(y == "Present")
    ) %>%
    mutate(taxa = selected_tax)
})

```

```{r}


df_plot <- df_metrics %>%
  left_join(df_class_counts, by = "taxa") %>%
  mutate(taxa = fct_reorder(taxa, auc))

# Left: AUC with CI
p_auc <- ggplot(df_plot, aes(x = auc, y = taxa)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = auc_lo, xmax = auc_hi), width = 0.2) +
  labs(x = "AUC [95% CI]", y = NULL) +
  theme_minimal()

# Right: Stacked bar for class balance
df_counts_long <- df_plot %>%
  select(taxa, n_present, n_absent) %>%
  pivot_longer(cols = c(n_present, n_absent), names_to = "class", values_to = "n") %>%
  mutate(class = ifelse(class == "n_present", "Present", "Absent"))

p_counts <- ggplot(df_counts_long, aes(x = n, y = taxa, fill = class)) +
  geom_col(position = "stack") +
  scale_fill_manual(values = c("Present" = "#20854EFF", "Absent" = "#BC3C29FF")) +
  labs(x = "Samples", y = NULL, fill = NULL) +
  theme_minimal() +
  theme(axis.text.y = element_blank())

# Combine

```

```{r}


cairo_pdf(here('output', paste0('figS3a_', format(Sys.Date(), "%Y%m%d"), '.pdf')), height = 10, width = 7)
p_auc + p_counts + plot_layout(widths = c(3, 1))
dev.off()


```

## Feature Importance Heatmap Full

```{r}

mat = df_imp %>%
  group_by(taxa) |> 
  ungroup() |> 
  select(compound, taxa, imp_mean) %>% 
  pivot_wider(names_from = taxa, values_from = imp_mean, values_fill = 0)

m = mat |> 
  select(-compound) |> 
  as.matrix()

rownames(m) = mat$compound
row_order = rownames(m)[ hclust(dist(m))$order ]
col_order = colnames(m)[hclust(dist(t(m)))$order]



qual_cat_order = c(
  'Primary',
  'Primary conjugate',
  'Primary sulfate',
  'Secondary',
  'Secondary conjugate',
  'Secondary sulfate',
  '3β-epimer',
  '7β-epimer',
  '12-epimer',
  'Oxo-intermediate',
  'Allo-epimer',
  '6α-hydroxylated',
  'Murine',
  'Other',
  
  'Substrate',
  'Microbial indole',
  'Kynurenine pathway',
  'Serotonin pathway',
  'Biogenic amine',
  'Microbial phenolic',
  'Microbial nucleoside',
  'Vitamin'
)


df_plot <- df_imp %>%
  mutate(category = factor(category, levels = qual_cat_order)) |> 
  filter(compound %in% rownames(m)) |> 
  mutate(
    taxa = factor(taxa, levels = col_order),
    compound = factor(compound, levels = row_order),
    sig_lab  = case_when(
      p_adj < 0.001 ~ "***",
      p_adj < 0.01  ~ "**",
      p_adj < 0.05  ~ "*",
      T ~ ""
    )
  ) |> 
  mutate(imp_mean = ifelse(cliffs_delta < 0, -imp_mean, imp_mean))


max(df_plot$imp_mean)
min(df_plot$imp_mean)

p_s3b = df_plot |> 
  ggplot(aes(x = taxa, y = compound)) +
  geom_tile(aes(fill = imp_mean)) +
  scale_fill_gradient2(high = '#b2182b', mid = 'white', low = '#2166ac', midpoint = 0, limits = c(-0.21,0.21)) +
  facet_grid(rows = vars(category), scales = "free_y", space = "free_y") +
  theme_bw(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    strip.text.y.right = element_text(angle = 0),
    legend.position = 'right'
  ) +
    labs(x = NULL, y = NULL, fill = "Scaled\nImportance")

```

```{r}

cairo_pdf(here('output', paste0('figS3b_', format(Sys.Date(), "%Y%m%d"), '.pdf')), height = 12, width = 16)
p_s3b
dev.off()

```
